#!/bin/sh
## Black        0;30     Dark Gray     1;30
## Red          0;31     Light Red     1;31
## Green        0;32     Light Green   1;32
## Brown/Orange 0;33     Yellow        1;33
## Blue         0;34     Light Blue    1;34
## Purple       0;35     Light Purple  1;35
## Cyan         0;36     Light Cyan    1;36
## Light Gray   0;37     White         1;37

color1='\033[1;31m'  # light red
color2='\033[0;31m'  # red
color3='\033[1;32m'  # light green
color4='\033[0;33m'  # green
color5='\033[1;34m'  # light blue
color6='\033[0;34m'  # blue
color7='\033[1;35m'  # light purple
color8='\033[0;35m'  # purple
color9='\033[1;36m'  # light cyan
color10='\033[0;36m'  # cyan
color11='\033[0;37m'  # light grey
color12='\033[1;37m'  # white
color13='\033[0;33m'  # brown
color14='\033[1;33m'  # yellow
nocolor='\033[0m'    # no color

#nodecount
total=`ps aux | grep -i heliumd | wc -l`
nodes=`expr $total - 1`

# AKcryptoGUY's mod
printf " ${color5} dddhoooooosdddddddhoooooosddd ${color1}  You've logged into a Helium Masternode.${nocolor}\n"
printf " ${color5} dddy      odddddddy      oddd ${color9}  No currency is stored on this server.${nocolor}\n"
printf " ${color5} dddy      odddddddy      oddd ${nocolor}\n"
printf " ${color5} dddy      odddddddy      oddd ${color13}  ------ General Information ------\n"
printf " ${color5} dddy      odddddddy      oddd ${color11}\n"
printf " ${color5} dddy       +++++++       oddd ${color11}  Hostname: $(hostname)\n"
printf " ${color5} dddy                     oddd ${color11}  Version: `lsb_release -s -d`${nocolor}\n"
printf " ${color5} dddy                     oddd ${color11}  `uname -srmo`${nocolor}\n"
printf " ${color5} dddy      odddddddy      oddd ${color11}\n"
printf " ${color5} dddh+     odddddddy      oddd ${color11}  Number of Masternodes: $nodes\n"
printf " ${color5} ddddddyso+odddddddy      oddd ${color11}  External IP: `ifconfig $(route | grep default | awk '{ print $8 }') | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'` \n"
printf " ${color5} ddddddddddddddddddy      oddd ${nocolor}\n"
printf " ${color5} ddddddddddddddddddy      oddd ${color13}  `date +"%A, %e %B %Y, %r"`${nocolor}\n"
printf " ${color5} ddddddddddddddddddddhh   hddd ${color1}  * Uptime: `/usr/bin/uptime -p` *${nocolor}\n"
